### ISSUE TITLE
可以做成一个exe软件吗

### ISSUE THREAD

**Issue by clairvoyant1218** [LuckyPuppy514/cloud-drive#1]
全部署过程有点麻烦 之前自己弄Raidrive失败了   上GitHub找挂载方法的肯定是常用方法碰壁了(●—●)   小白希望有个一键安装方法    谢谢

**Comment by LuckyPuppy514** [comment]
exe? 你是 windows 用么，我这个脚本都是 linux 用的

**Comment by clairvoyant1218** [comment]
> 

是啊 面向大众的就应该是把这30T的网盘挂载win本地盘目前的clouddrive和官方内测都有不足   alist方法卡在raidrive上了   做成桌面端受众会很多

**Comment by LuckyPuppy514** [comment]
不好意思，我这个是利用 webdav + rclone + mergerfs 挂载网盘到 linux，方便 Emby/Plex/Jellyfin 等看视频的
你要 windows 挂在网盘，可以试试 WebDrive 和 NetDrive 这两个软件
